// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// User holds the user retrieved data
type User struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32                `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Year                 int32                `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Gpa                  int32                `protobuf:"varint,4,opt,name=gpa,proto3" json:"gpa,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *User) GetGpa() int32 {
	if m != nil {
		return m.Gpa
	}
	return 0
}

func (m *User) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

func (*User) XXX_MessageName() string {
	return "user.User"
}
func init() {
	proto.RegisterType((*User)(nil), "user.User")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0x4d, 0x4a, 0xc5, 0x30,
	0x14, 0x85, 0x49, 0x9b, 0x0a, 0xa6, 0x22, 0x92, 0x51, 0xe8, 0x40, 0x8b, 0xa3, 0x4e, 0x4c, 0x41,
	0xc7, 0x4e, 0x5c, 0x42, 0xb1, 0x63, 0x49, 0x4d, 0x8c, 0x81, 0xc6, 0x84, 0xfc, 0x0c, 0x5c, 0x85,
	0xdb, 0x72, 0x1f, 0x6f, 0x23, 0x8f, 0xdc, 0x50, 0xde, 0xec, 0x3b, 0xe7, 0x7e, 0x17, 0x0e, 0x21,
	0x39, 0xaa, 0xc0, 0x7d, 0x70, 0xc9, 0x51, 0x5c, 0x78, 0x78, 0xd2, 0x26, 0x7d, 0xe7, 0x8d, 0x7f,
	0x3a, 0x3b, 0x6b, 0xa7, 0xdd, 0x0c, 0xc7, 0x2d, 0x7f, 0x41, 0x82, 0x00, 0x54, 0x9f, 0x86, 0x07,
	0xed, 0x9c, 0xde, 0xd5, 0xc5, 0x4a, 0xc6, 0xaa, 0x98, 0x84, 0xf5, 0x55, 0x78, 0xfc, 0x43, 0x04,
	0xaf, 0x51, 0x05, 0x4a, 0x09, 0xfe, 0x11, 0x56, 0x31, 0x34, 0xa2, 0xe9, 0x7a, 0x01, 0xa6, 0xb7,
	0xa4, 0x31, 0x92, 0x35, 0x23, 0x9a, 0xba, 0xa5, 0x31, 0xb2, 0x38, 0xbf, 0x4a, 0x04, 0xd6, 0x42,
	0x03, 0x4c, 0xef, 0x48, 0xab, 0xbd, 0x60, 0x18, 0xaa, 0x82, 0xf4, 0x95, 0xdc, 0xec, 0x22, 0xa6,
	0x8f, 0xec, 0xa5, 0x48, 0x4a, 0xb2, 0x6e, 0x44, 0x53, 0xff, 0x3c, 0xf0, 0x3a, 0x85, 0x1f, 0x53,
	0xf8, 0xfb, 0x31, 0x65, 0xe9, 0x8b, 0xbf, 0x56, 0xfd, 0x0d, 0xff, 0x9f, 0xee, 0xd1, 0x76, 0x05,
	0xda, 0xcb, 0x39, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x24, 0x77, 0x3b, 0x02, 0x01, 0x00, 0x00,
}
