dist: xenial

language: go

go:
  - 1.12.x

services:
  - docker

env:
  - DEP_VERSION="0.5.0"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - docker pull postgres
  - docker run --name pg --privileged -e POSTGRES_PASSWORD=docker -e POSTGRES_DB=test --rm -p 5433:5432 postgres

git:
  depth: 1

install:
  - dep ensure

notifications:
  email: false

script:
  - go test -v ./...  # Run all the tests with the race detector enabled