dist: xenial

language: go

go:
  - 1.12.x

services:
  - docker

before_install:
  - docker run --name pg --privileged --rm -e POSTGRES_PASSWORD=docker -p 5432:5432 -v $HOME/docker/volumes/postgres:/var/lib/postgresql/data postgres

git:
  depth: 1

install: true

notifications:
  email: false

before_script:
  - dep ensure

script:
  - go test -v ./...  # Run all the tests with the race detector enabled