dist: xenial

language: go

go:
  - 1.12.x

services:
  - docker

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - docker pull postgres
  - docker run --name pg --privileged -e POSTGRES_PASSWORD=docker -e POSTGRES_DB=test --rm -p 5433:5432 postgres
  - docker ps -a

git:
  depth: 1

install:
  - dep ensure

notifications:
  email: false

script:
  - go test -v ./...  # Run all the tests with the race detector enabled